version: "3.8"
services:
  api:
    build: ./udlf-web-api
    container_name: api
    ports:
      - "8080:8080"

  front:
    build: ./front
    container_name: front
    ports:
      - "3000:3000"
    depends_on:
      - api
