#!/bin/bash

# UDLF Web Application - Quick Setup Script
# This script sets up the environment in 3 simple steps

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}🚀 UDLF Web Application - Quick Setup${NC}"
echo "======================================"
echo ""

# Step 1: Check if .env exists
if [ -f ".env" ]; then
    echo -e "${YELLOW}⚠️  .env file already exists${NC}"
    read -p "Do you want to overwrite it? (y/n): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

# Step 2: Get HOST_UDLF_PATH from user
echo -e "${BLUE}📁 Step 1: Configure datasets directory${NC}"
echo "Enter the path to your datasets directory:"
echo "Example: /Users/username/datasets or /home/user/datasets"
echo ""

while true; do
    read -p "Datasets path: " HOST_UDLF_PATH
    
    # Expand tilde and variables
    HOST_UDLF_PATH=$(eval echo "$HOST_UDLF_PATH")
    
    if [ -d "$HOST_UDLF_PATH" ]; then
        echo -e "${GREEN}✅ Directory found: $HOST_UDLF_PATH${NC}"
        break
    else
        echo -e "${YELLOW}❌ Directory not found: $HOST_UDLF_PATH${NC}"
        read -p "Create this directory? (y/n): " create_dir
        if [[ $create_dir =~ ^[Yy]$ ]]; then
            mkdir -p "$HOST_UDLF_PATH"
            echo -e "${GREEN}✅ Directory created: $HOST_UDLF_PATH${NC}"
            break
        fi
    fi
done

# Step 3: Create .env file
echo ""
echo -e "${BLUE}⚙️  Step 2: Creating .env file${NC}"

# Create .env from template
cat > .env << EOF
# UDLF Web Application - Environment Configuration
# Generated by quick-setup.sh

# REQUIRED: Datasets directory path
HOST_UDLF_PATH=$HOST_UDLF_PATH

# All other variables are pre-configured
API_PORT=8080
API_HOST=localhost
FRONTEND_PORT=3000
FRONTEND_HOST=localhost
NODE_ENV=development
API_INTERNAL_URL=http://api:8080
FRONTEND_INTERNAL_URL=http://front:3000
NEXT_PUBLIC_URL_API_LOCAL=http://localhost:8080
APP_DATASETS_PATH=/app/datasets
EXECUTABLE_PATH=/app/udlf/bin/udlf
EOF

echo -e "${GREEN}✅ .env file created successfully!${NC}"

# Step 4: Show next steps
echo ""
echo -e "${BLUE}🎉 Setup Complete!${NC}"
echo "=================="
echo ""
echo -e "${GREEN}Next steps:${NC}"
echo "1. Run: docker-compose up --build"
echo "2. Open: http://localhost:3000"
echo "3. API available at: http://localhost:8080"
echo ""
echo -e "${YELLOW}Configuration:${NC}"
echo "• Datasets path: $HOST_UDLF_PATH"
echo "• Frontend port: 3000"
echo "• API port: 8080"
echo ""
echo -e "${BLUE}Happy coding! 🚀${NC}"
